// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnIRepository.Models.NorthWind;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Title { get; set; }

    /// <summary>
    /// 尊稱
    /// </summary>
    public string TitleOfCourtesy { get; set; }

    public DateTime? BirthDate { get; set; }

    /// <summary>
    /// 僱用日期
    /// </summary>
    public DateTime? HireDate { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    /// <summary>
    /// 所在地區
    /// </summary>
    public string Region { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string HomePhone { get; set; }

    /// <summary>
    /// 分機
    /// </summary>
    public string Extension { get; set; }

    public byte[] Photo { get; set; }

    public string Notes { get; set; }

    /// <summary>
    /// 上級
    /// </summary>
    public int? ReportsTo { get; set; }

    public string PhotoPath { get; set; }

    public virtual ICollection<Employee> InverseReportsToNavigation { get; set; } = new List<Employee>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Employee ReportsToNavigation { get; set; }

    public virtual ICollection<Territory> Territories { get; set; } = new List<Territory>();
}